# fly.toml app configuration file generated for iqra-converter on 2026-01-30T00:18:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iqra-converter'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'INFO'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

[http_service.machine_checks]

[http_service.session_affinity]
  enabled = true

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'performance'
  cpus = 1
  memory_mb = 2048
